// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjT2PPnAiTCFIuoG627ln00BDvvyqm3mg',
    appId: '1:453196205507:web:ece4328a98bff7691cc176',
    messagingSenderId: '453196205507',
    projectId: 'scout-e844e',
    authDomain: 'scout-e844e.firebaseapp.com',
    storageBucket: 'scout-e844e.appspot.com',
    measurementId: 'G-W2G7RPY2WD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwe04Tsx5ZaByJdQGejGxDuUOBXARCRdw',
    appId: '1:453196205507:android:d687f1222ce85d1d1cc176',
    messagingSenderId: '453196205507',
    projectId: 'scout-e844e',
    storageBucket: 'scout-e844e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCciqXiwrCIs_dzcMJFjFAZQj08kpee1ZE',
    appId: '1:453196205507:ios:18deb9fdafe9ee041cc176',
    messagingSenderId: '453196205507',
    projectId: 'scout-e844e',
    storageBucket: 'scout-e844e.appspot.com',
    iosClientId: '453196205507-honavligoevn9c6j4pbuuuam94i6qrtl.apps.googleusercontent.com',
    iosBundleId: 'com.example.scout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCciqXiwrCIs_dzcMJFjFAZQj08kpee1ZE',
    appId: '1:453196205507:ios:18deb9fdafe9ee041cc176',
    messagingSenderId: '453196205507',
    projectId: 'scout-e844e',
    storageBucket: 'scout-e844e.appspot.com',
    iosClientId: '453196205507-honavligoevn9c6j4pbuuuam94i6qrtl.apps.googleusercontent.com',
    iosBundleId: 'com.example.scout',
  );
}
